# Generated by Django 5.1.6 on 2025-02-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'Docente'), ('director', 'Directivo'), ('student', 'Estudiante')], default='director', max_length=20),
        ),
    ]
