# Generated by Django 5.1.6 on 2025-05-23 23:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Defecto', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='Defecto', max_length=100, null=True)),
                ('last_name', models.CharField(default='Defecto', max_length=100)),
                ('second_last_name', models.CharField(blank=True, default='Defecto', max_length=100, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('email', models.EmailField(default='default@gmail.com', max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Administrativo',
                'verbose_name_plural': 'Administrativos',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Curso sin nombre', max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('academic_year', models.CharField(default='2023-2024', max_length=9)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='CourseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Asignación de Materia',
                'verbose_name_plural': 'Asignaciones de Materias',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('date_assigned', models.DateTimeField(default=django.utils.timezone.now)),
                ('period', models.PositiveSmallIntegerField(default=1)),
                ('year', models.CharField(default='2023', max_length=4)),
                ('comments', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('categoria', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Defecto', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='Defecto', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='Defecto', max_length=100, null=True)),
                ('second_last_name', models.CharField(blank=True, default='Defecto', max_length=100, null=True)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(default='default@gmail.com', max_length=254, unique=True)),
                ('student_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Defecto', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='Defecto', max_length=100, null=True)),
                ('last_name', models.CharField(default='Defecto', max_length=100)),
                ('second_last_name', models.CharField(blank=True, default='Defecto', max_length=100, null=True)),
                ('title', models.CharField(default='Defecto', max_length=50)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(default='default@gmail.com', max_length=254, unique=True)),
                ('specialization', models.CharField(default='General', max_length=100)),
                ('teacher_id', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
    ]
