# Generated by Django 5.1.6 on 2025-03-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_subject_remove_course_teacher_coursesubject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='academic.teacher'),
        ),
    ]
