# Generated by Django 5.1.6 on 2025-05-25 07:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_gradeentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradeentry',
            options={'verbose_name': 'Entrada de Calificación', 'verbose_name_plural': 'Entradas de Calificaciones'},
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='late_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.student'),
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Barrio/Zona'),
        ),
        migrations.AddField(
            model_name='student',
            name='socioeconomic_status',
            field=models.CharField(blank=True, choices=[('BAJO', 'Bajo'), ('MEDIO_BAJO', 'Medio Bajo'), ('MEDIO', 'Medio'), ('MEDIO_ALTO', 'Medio Alto'), ('ALTO', 'Alto')], max_length=50, verbose_name='Nivel Socioeconómico'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('assignment_type', models.CharField(choices=[('EXAMEN', 'Examen'), ('QUIZ', 'Quiz'), ('TAREA', 'Tarea'), ('PROYECTO', 'Proyecto'), ('PARTICIPACION', 'Participación'), ('LABORATORIO', 'Laboratorio'), ('ENSAYO', 'Ensayo'), ('PRESENTACION', 'Presentación'), ('OTRO', 'Otro')], default='TAREA', max_length=20)),
                ('date_assigned', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(default=1.0, help_text='Peso relativo en la nota del periodo')),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('period', models.PositiveSmallIntegerField(default=1)),
                ('year', models.CharField(default='2024', max_length=4)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Actividad/Tarea',
                'verbose_name_plural': 'Actividades/Tareas',
                'ordering': ['-date_assigned'],
            },
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.assignment'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeentry',
            unique_together={('assignment', 'student')},
        ),
        migrations.RemoveField(
            model_name='gradeentry',
            name='label',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, help_text='Justificación de ausencia o comentarios')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academic.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-date'],
                'unique_together': {('student', 'date', 'subject')},
            },
        ),
    ]
