# Generated by Django 5.1.6 on 2025-03-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_course_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
