# Generated by Django 5.1.6 on 2025-05-25 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_remove_assignment_subject_assignment_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.coursesubject'),
        ),
    ]
