# Generated by Django 5.1.6 on 2025-05-27 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_assignment_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeentry',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='academic.grade'),
        ),
    ]
