# Generated by Django 5.1.6 on 2025-03-12 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_grado_course_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academic.grado'),
            preserve_default=False,
        ),
    ]
