# Generated by Django 5.1.6 on 2025-05-27 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_gradeentry_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
