# Generated by Django 5.1.6 on 2025-05-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_gradeentry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
