# Generated by Django 5.1.6 on 2025-06-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_gradeentry_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Número interno del periodo (1, 2, 3…)')),
                ('name', models.CharField(help_text="Nombre descriptivo (p. ej. 'Primer Periodo', 'Segundo Periodo')", max_length=50)),
                ('start_date', models.DateField(help_text='Fecha de inicio del periodo')),
                ('end_date', models.DateField(help_text='Fecha de fin del periodo')),
                ('edit_deadline', models.DateField(help_text='Fecha límite en la que el docente puede editar notas para este periodo')),
                ('academic_year', models.CharField(help_text="Año académico al que pertenece (p. ej. '2024-2025')", max_length=9)),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'ordering': ['academic_year', 'number'],
                'unique_together': {('number', 'academic_year')},
            },
        ),
    ]
