# Generated by Django 5.1.6 on 2025-06-25 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_academicperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={},
        ),
        migrations.AlterField(
            model_name='gradeentry',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='academic.assignment'),
        ),
    ]
