# Generated by Django 5.1.6 on 2025-06-27 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academic.grado'),
        ),
    ]
