# Generated by Django 5.1.6 on 2025-06-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_alter_course_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Foto de perfil del administrador', null=True, upload_to='administrators/profile_pictures/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Foto de perfil del profesor', null=True, upload_to='teachers/profile_pictures/'),
        ),
    ]
